# permissions for end users to edit coralogixloggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coralogixlogger-editor-role
rules:
- apiGroups:
  - loggers.coralogix.com
  resources:
  - coralogixloggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loggers.coralogix.com
  resources:
  - coralogixloggers/status
  verbs:
  - get
