# permissions for end users to view coralogixloggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coralogixlogger-viewer-role
rules:
- apiGroups:
  - loggers.coralogix.com
  resources:
  - coralogixloggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loggers.coralogix.com
  resources:
  - coralogixloggers/status
  verbs:
  - get
