apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: coralogixloggers.coralogix.com
spec:
  group: coralogix.com
  names:
    kind: CoralogixLogger
    listKind: CoralogixLoggerList
    plural: coralogixloggers
    singular: coralogixlogger
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: CoralogixLogger is the Schema for the coralogixloggers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CoralogixLoggerSpec defines the desired state of CoralogixLogger
            properties:
              cluster_name:
                description: Cluster name
                title: Cluster Name
                type: string
              private_key:
                description: Coralogix Private Key
                title: Private Key
                type: string
                format: password
                pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-z]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                minLength: 36
                maxLength: 36
            required:
            - cluster_name
            - private_key
            type: object
          status:
            description: CoralogixLoggerStatus defines the observed state of CoralogixLogger
            properties:
              serviceAccount:
                description: ServiceAccount name
                title: ServiceAccount
                type: string
              clusterRole:
                description: ClusterRole
                title: ClusterRole
                type: string
              clusterRoleBinding:
                description: ClusterRoleBinding name
                title: ClusterRoleBinding
                type: string
              daemonSet:
                description: DaemonSet name
                title: DaemonSet
                type: string
            required:
            - serviceAccount
            - clusterRole
            - clusterRoleBinding
            - daemonSet
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
